// Semantic color system with default values
export const DEFAULT_COLORS = {
  // Primary Button
  'primary-bg': '#3B82F6',
  'primary-text': '#FFFFFF',
  'primary-icon': '#FFFFFF',
  'primary-hover-bg': '#2563EB',
  'primary-pressed-bg': '#1D4ED8',
  'primary-disabled-bg': '#93C5FD',
  'focused-border': '#3B82F6',

  // Secondary Button
  'secondary-bg': '#F3F4F6',
  'secondary-border': '#E5E7EB',
  'secondary-text': '#1F2937',
  'secondary-icon': '#1F2937',
  'secondary-hover-bg': '#E5E7EB',
  'secondary-pressed-bg': '#D1D5DB',
  'secondary-disabled-bg': '#F9FAFB',

  // Ghost Button
  'ghost-bg': 'transparent',
  'ghost-text': '#1F2937',
  'ghost-icon': '#1F2937',
  'ghost-hover-bg': '#F3F4F6',
  'ghost-pressed-bg': '#E5E7EB',
  'ghost-disabled-bg': 'transparent',

  // Background
  'bg-white': '#FFFFFF',
  'bg-neutral-subtle': '#F9FAFB',
  'bg-neutral-light': '#F3F4F6',
  'bg-neutral': '#E5E7EB',
  'bg-accent': '#FEF3C7',
  'bg-accent-mid': '#FDE68A',
  'bg-brand-subtle': '#EFF6FF',
  'bg-table': '#FFFFFF',
  'bg-secondary': '#F3F4F6',
  'bg-brand-light': '#DBEAFE',
  'bg-brand-mid': '#93C5FD',
  'bg-brand': '#3B82F6',
  'bg-neutral-mid': '#9CA3AF',
  'bg-neutral-strong': '#4B5563',
  'bg-header': '#1F2937',
  'bg-superlative': '#10B981',
  'bg-button': '#3B82F6',

  // Foreground
  'fg-heading': '#111827',
  'fg-body': '#374151',
  'fg-link-secondary': '#6B7280',
  'fg-caption': '#9CA3AF',
  'fg-stroke-ui': '#D1D5DB',
  'fg-link': '#3B82F6',
  'fg-stroke-ui-inverse': '#4B5563',
  'fg-heading-inverse': '#FFFFFF',
  'fg-body-inverse': '#F3F4F6',
  'fg-caption-inverse': '#D1D5DB',
  'fg-table-border': '#E5E7EB',
  'fg-stroke-default': '#D1D5DB',
  'fg-divider': '#E5E7EB',
  'fg-stroke-inverse': '#4B5563',
  'fg-stroke-dark-inverse': '#1F2937',
  'fg-feedback-error': '#EF4444',
  'fg-feedback-warning': '#F59E0B',
  'fg-feedback-success': '#10B981',

  // Superlative
  'superlative-primary': '#3B82F6',
  'superlative-secondary': '#10B981',
} as const

export const COLOR_CATEGORIES = {
  'Primary Button': [
    'primary-bg',
    'primary-text',
    'primary-icon',
    'primary-hover-bg',
    'primary-pressed-bg',
    'primary-disabled-bg',
    'focused-border',
  ],
  'Secondary Button': [
    'secondary-bg',
    'secondary-border',
    'secondary-text',
    'secondary-icon',
    'secondary-hover-bg',
    'secondary-pressed-bg',
    'secondary-disabled-bg',
  ],
  'Ghost Button': [
    'ghost-bg',
    'ghost-text',
    'ghost-icon',
    'ghost-hover-bg',
    'ghost-pressed-bg',
    'ghost-disabled-bg',
  ],
  'Background': [
    'bg-white',
    'bg-neutral-subtle',
    'bg-neutral-light',
    'bg-neutral',
    'bg-accent',
    'bg-accent-mid',
    'bg-brand-subtle',
    'bg-table',
    'bg-secondary',
    'bg-brand-light',
    'bg-brand-mid',
    'bg-brand',
    'bg-neutral-mid',
    'bg-neutral-strong',
    'bg-header',
    'bg-superlative',
    'bg-button',
  ],
  'Foreground': [
    'fg-heading',
    'fg-body',
    'fg-link-secondary',
    'fg-caption',
    'fg-stroke-ui',
    'fg-link',
    'fg-stroke-ui-inverse',
    'fg-heading-inverse',
    'fg-body-inverse',
    'fg-caption-inverse',
    'fg-table-border',
    'fg-stroke-default',
    'fg-divider',
    'fg-stroke-inverse',
    'fg-stroke-dark-inverse',
    'fg-feedback-error',
    'fg-feedback-warning',
    'fg-feedback-success',
  ],
  'Superlative': ['superlative-primary', 'superlative-secondary'],
} as const

export const COLOR_LABELS: Record<string, string> = {
  'primary-bg': 'Primary Background',
  'primary-text': 'Primary Text',
  'primary-icon': 'Primary Icon',
  'primary-hover-bg': 'Primary Hover',
  'primary-pressed-bg': 'Primary Pressed',
  'primary-disabled-bg': 'Primary Disabled',
  'focused-border': 'Focused Border',
  'secondary-bg': 'Secondary Background',
  'secondary-border': 'Secondary Border',
  'secondary-text': 'Secondary Text',
  'secondary-icon': 'Secondary Icon',
  'secondary-hover-bg': 'Secondary Hover',
  'secondary-pressed-bg': 'Secondary Pressed',
  'secondary-disabled-bg': 'Secondary Disabled',
  'ghost-bg': 'Ghost Background',
  'ghost-text': 'Ghost Text',
  'ghost-icon': 'Ghost Icon',
  'ghost-hover-bg': 'Ghost Hover',
  'ghost-pressed-bg': 'Ghost Pressed',
  'ghost-disabled-bg': 'Ghost Disabled',
  'bg-white': 'White',
  'bg-neutral-subtle': 'Neutral Subtle',
  'bg-neutral-light': 'Neutral Light',
  'bg-neutral': 'Neutral',
  'bg-accent': 'Accent',
  'bg-accent-mid': 'Accent Mid',
  'bg-brand-subtle': 'Brand Subtle',
  'bg-table': 'Table',
  'bg-secondary': 'Secondary',
  'bg-brand-light': 'Brand Light',
  'bg-brand-mid': 'Brand Mid',
  'bg-brand': 'Brand',
  'bg-neutral-mid': 'Neutral Mid',
  'bg-neutral-strong': 'Neutral Strong',
  'bg-header': 'Header',
  'bg-superlative': 'Superlative',
  'bg-button': 'Button',
  'fg-heading': 'Heading',
  'fg-body': 'Body',
  'fg-link-secondary': 'Link Secondary',
  'fg-caption': 'Caption',
  'fg-stroke-ui': 'Stroke UI',
  'fg-link': 'Link',
  'fg-stroke-ui-inverse': 'Stroke UI Inverse',
  'fg-heading-inverse': 'Heading Inverse',
  'fg-body-inverse': 'Body Inverse',
  'fg-caption-inverse': 'Caption Inverse',
  'fg-table-border': 'Table Border',
  'fg-stroke-default': 'Stroke Default',
  'fg-divider': 'Divider',
  'fg-stroke-inverse': 'Stroke Inverse',
  'fg-stroke-dark-inverse': 'Stroke Dark Inverse',
  'fg-feedback-error': 'Error',
  'fg-feedback-warning': 'Warning',
  'fg-feedback-success': 'Success',
  'superlative-primary': 'Primary',
  'superlative-secondary': 'Secondary',
}
